version: "3"

services:
  db:
    restart: always
    image: mysql
    container_name: database
    ports:
      - "6603:3306"
    volumes:
      - ~/mysql/database/mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=photo123
      - MYSQL_DATABASE=photodbs

  storage:
    restart: always
    image: quay.io/minio/minio
    container_name: minio1
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER= # <-----INSERT USERNAME
      - MINIO_ROOT_PASSWORD= # <-----INSERT PASSWORD
    command: server /data --console-address ":9001"

  app_server:
    restart: always
    image: <DOCKERUSERNAME>/photogallery:v1 # <-----INSERT DOCKER USERNAME (e.g,. johndoe/photogallery:v1)
    container_name: appserver
    ports:
      - "5000:5000"
    depends_on:
      - "db"
      - "storage"
    environment:
      - BUCKET_NAME=photogallery
      - ACCESS_KEY_USERNAME= # <-----INSERT USERNAME
      - SECRET_KEY_PASSWORD= # <-----INSERT PASSWORD
      - STORAGE_HOST=storage
      - STORAGE_HOST_PORT=9000
      - STORAGE_HOST_EXT=localhost
      - STORAGE_PORT_EXT=9000
      - DB_HOSTNAME=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=photo123
      - DB_NAME=photodbs
      - DB_TABLE=photogallery
